steps:
  # Copy Maven dependencies to volume mavenrepo
  - name: gcr.io/cloud-builders/gsutil
    volumes:
      - name: 'mavenrepo'
        path: '/root/.m2'
    args:
      - -m
      - rsync
      - -r
      - gs://mayhoo-mavenrepo/.m2
      - /root/.m2

  # Run the Maven build
  - name: maven:3.6.3-jdk-11-slim
    volumes:
      - name: 'mavenrepo'
        path: '/root/.m2'
    entrypoint: 'mvn'
    args:
      - clean
      - install
      - -DskipTests

  # Preserve the Maven dependencies into the bucket
  - name: gcr.io/cloud-builders/gsutil
    volumes:
      - name: 'mavenrepo'
        path: '/root/.m2'
    args:
      - -m
      - rsync
      - -d
      - -r
      - /root/.m2
      - gs://mayhoo-mavenrepo/.m2
